### ISSUE TITLE
PCB questions

### ISSUE THREAD

**Issue by gekomod** [v-ivanyshyn/mqb-steering-wheel-adapter#3]
Hi, what is this hole marked in the picture? I can't find anything

![IMG_20211208_185728](https://user-images.githubusercontent.com/3285747/145259695-49913214-889e-456c-b955-1c6b05cc217e.jpg)
![IMG_20211208_190124](https://user-images.githubusercontent.com/3285747/145259866-9ed5d9de-5486-4afe-a44d-e3062b983d53.jpg)

**Comment by Georgy-Garnov** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/3997989/145869875-9e239e20-6446-4309-858d-465e553cdf23.png)
